version: '3.8'

services:
  app:
    build:
      context: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MODE=prod
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
